version = '2'

[run]
concurrency = 4
tests = false

[linters]
default = 'none'
enable = [
  'depguard',
  'gocritic',
  'gocyclo',
  'gosec',
  'govet',
  'ineffassign',
  'misspell',
  'staticcheck',
  'unconvert',
  'unparam',
  'unused'
]

[linters.settings]
[linters.settings.depguard]
  [linters.settings.depguard.rules.main]
    allow = [
      "$gostd",
      "github.com/h2non/bimg",
      "github.com/rs/cors",
      "github.com/throttled/throttled/v2",
      "github.com/throttled/throttled/v2/store/memstore",
      "github.com/h2non/filetype",
    ]

[linters.settings.goconst]
min-len = 2
min-occurrences = 2

[linters.settings.gocyclo]
min-complexity = 20

[linters.settings.misspell]
locale = 'US'

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
